name: Sanity Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Sanity CLI
        run: pnpm install -g @sanity/cli
      - name: Deploy Studio
        run: pnpm deploy
